using dotNetLab;
using dotNetLab.Common;
using dotNetLab.Common.ModernUI;
using dotNetLab.Widgets;
using dotNetLab.Widgets.UIBinding;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;

namespace shikii.VisionJob
{
	public class TCPNetConnectForm : SessionPage
	{
		public string TCPTABLENAME = "TCP";

		private readonly string SERIALPORTTABLENAME = "SerialPort";

		private MobileTextBox mobileTextBox3;

		private MobileTextBox mobileTextBox1;

		private MobileTextBox mobileTextBox2;

		private TextBlock textBlock9;

		private TextBlock textBlock8;

		private Card card1;

		private TextBlock textBlock1;

		private Card card2;

		private TextBlock textBlock2;

		private TextBlock textBlock3;

		private MobileTextBox txb_LoopGapTime;

		private TextBlock textBlock4;

		private TextBlock textBlock5;

		private MobileTextBox txb_COM;

		private MobileTextBox txb_BaudRate;

		private TextBlock textBlock11;

		private TextBlock textBlock10;

		private TextBlock textBlock6;

		private MobileTextBox txb_Parity;

		private MobileTextBox txb_StopBits;

		private MobileTextBox txb_DataBits;

		private TextBlock textBlock7;

		protected override void prepareCtrls()
		{
			base.prepareCtrls();
			InitializeComponent();
		}

		protected override void prepareAppearance()
		{
			base.prepareAppearance();
			base.EnableDrawUpDownPattern = true;
			base.Img_Up = UI.RibbonSchoolStuff;
		}

		protected override void prepareData()
		{
			base.prepareData();
			base.CompactDB.GetAllTableNames();
			if (!base.CompactDB.AllTableNames.Contains(TCPTABLENAME))
			{
				base.CompactDB.CreateKeyValueTable(TCPTABLENAME);
			}
			if (!base.CompactDB.AllTableNames.Contains(SERIALPORTTABLENAME))
			{
				base.CompactDB.CreateKeyValueTable(SERIALPORTTABLENAME);
			}
			base.CompactDB.TargetTable = TCPTABLENAME;
			List<string> nameColumnValues = base.CompactDB.GetNameColumnValues(base.CompactDB.TargetTable);
			if (!nameColumnValues.Contains("IP"))
			{
				base.CompactDB.Write("IP", "127.0.0.1");
			}
			if (!nameColumnValues.Contains("Port"))
			{
				base.CompactDB.Write("Port", "8040");
			}
			if (!nameColumnValues.Contains("LoopGapTime"))
			{
				base.CompactDB.Write("LoopGapTime", "100");
			}
			base.CompactDB.TargetTable = SERIALPORTTABLENAME;
			nameColumnValues = base.CompactDB.GetNameColumnValues(base.CompactDB.TargetTable);
			if (!nameColumnValues.Contains("COM"))
			{
				base.CompactDB.Write("COM", "COM1");
			}
			if (!nameColumnValues.Contains("BaudRate"))
			{
				base.CompactDB.Write("BaudRate", "8040");
			}
			if (!nameColumnValues.Contains("LoopGapTime"))
			{
				base.CompactDB.Write("LoopGapTime", "100");
			}
			if (!nameColumnValues.Contains("DataBits"))
			{
				base.CompactDB.Write("DataBits", "8");
			}
			if (!nameColumnValues.Contains("StopBits"))
			{
				base.CompactDB.Write("StopBits", "8");
			}
			if (!nameColumnValues.Contains("Parity"))
			{
				base.CompactDB.Write("Parity", "0");
			}
			R.CompactDB.TargetTable = R.CompactDB.DefaultTable;
		}

		private void InitializeComponent()
		{
			dotNetLab.Widgets.UIBinding.UIElementBinderInfo uIElementBinderInfo = new dotNetLab.Widgets.UIBinding.UIElementBinderInfo();
			dotNetLab.Widgets.UIBinding.UIElementBinderInfo uIElementBinderInfo2 = new dotNetLab.Widgets.UIBinding.UIElementBinderInfo();
			dotNetLab.Widgets.UIBinding.UIElementBinderInfo uIElementBinderInfo3 = new dotNetLab.Widgets.UIBinding.UIElementBinderInfo();
			dotNetLab.Widgets.UIBinding.UIElementBinderInfo uIElementBinderInfo4 = new dotNetLab.Widgets.UIBinding.UIElementBinderInfo();
			dotNetLab.Widgets.UIBinding.UIElementBinderInfo uIElementBinderInfo5 = new dotNetLab.Widgets.UIBinding.UIElementBinderInfo();
			dotNetLab.Widgets.UIBinding.UIElementBinderInfo uIElementBinderInfo6 = new dotNetLab.Widgets.UIBinding.UIElementBinderInfo();
			dotNetLab.Widgets.UIBinding.UIElementBinderInfo uIElementBinderInfo7 = new dotNetLab.Widgets.UIBinding.UIElementBinderInfo();
			dotNetLab.Widgets.UIBinding.UIElementBinderInfo uIElementBinderInfo8 = new dotNetLab.Widgets.UIBinding.UIElementBinderInfo();
			dotNetLab.Widgets.UIBinding.UIElementBinderInfo uIElementBinderInfo9 = new dotNetLab.Widgets.UIBinding.UIElementBinderInfo();
			mobileTextBox3 = new dotNetLab.Widgets.MobileTextBox();
			mobileTextBox1 = new dotNetLab.Widgets.MobileTextBox();
			mobileTextBox2 = new dotNetLab.Widgets.MobileTextBox();
			txb_LoopGapTime = new dotNetLab.Widgets.MobileTextBox();
			txb_COM = new dotNetLab.Widgets.MobileTextBox();
			txb_BaudRate = new dotNetLab.Widgets.MobileTextBox();
			txb_DataBits = new dotNetLab.Widgets.MobileTextBox();
			txb_StopBits = new dotNetLab.Widgets.MobileTextBox();
			txb_Parity = new dotNetLab.Widgets.MobileTextBox();
			textBlock9 = new dotNetLab.Widgets.TextBlock();
			textBlock8 = new dotNetLab.Widgets.TextBlock();
			textBlock7 = new dotNetLab.Widgets.TextBlock();
			card1 = new dotNetLab.Widgets.Card();
			textBlock1 = new dotNetLab.Widgets.TextBlock();
			card2 = new dotNetLab.Widgets.Card();
			textBlock2 = new dotNetLab.Widgets.TextBlock();
			textBlock11 = new dotNetLab.Widgets.TextBlock();
			textBlock10 = new dotNetLab.Widgets.TextBlock();
			textBlock6 = new dotNetLab.Widgets.TextBlock();
			textBlock3 = new dotNetLab.Widgets.TextBlock();
			textBlock4 = new dotNetLab.Widgets.TextBlock();
			textBlock5 = new dotNetLab.Widgets.TextBlock();
			card1.SuspendLayout();
			card2.SuspendLayout();
			SuspendLayout();
			tipper.Location = new System.Drawing.Point(357, 467);
			mobileTextBox3.ActiveColor = System.Drawing.Color.Cyan;
			mobileTextBox3.BackColor = System.Drawing.Color.Transparent;
			uIElementBinderInfo.DBEngineIndex = 0;
			uIElementBinderInfo.EnableCheckBox_One_Zero = false;
			uIElementBinderInfo.FieldName = "Val";
			uIElementBinderInfo.Filter = "Name='LoopGapTime' ";
			uIElementBinderInfo.Ptr = null;
			uIElementBinderInfo.StoreInDB = true;
			uIElementBinderInfo.StoreIntoDBRealTime = true;
			uIElementBinderInfo.TableName = "TCP";
			uIElementBinderInfo.ThisControl = mobileTextBox3;
			mobileTextBox3.DataBindingInfo = uIElementBinderInfo;
			mobileTextBox3.DoubleValue = double.NaN;
			mobileTextBox3.EnableMobileRound = false;
			mobileTextBox3.EnableNullValue = false;
			mobileTextBox3.FillColor = System.Drawing.Color.Transparent;
			mobileTextBox3.FloatValue = float.NaN;
			mobileTextBox3.Font = new System.Drawing.Font("微软雅黑", 13f);
			mobileTextBox3.ForeColor = System.Drawing.Color.Black;
			mobileTextBox3.GreyPattern = false;
			mobileTextBox3.IntValue = -2147483648;
			mobileTextBox3.LineThickness = 2f;
			mobileTextBox3.Location = new System.Drawing.Point(187, 130);
			mobileTextBox3.MainBindableProperty = "";
			mobileTextBox3.Name = "mobileTextBox3";
			mobileTextBox3.Radius = -1;
			mobileTextBox3.Size = new System.Drawing.Size(187, 30);
			mobileTextBox3.StaticColor = System.Drawing.Color.DodgerBlue;
			mobileTextBox3.TabIndex = 7;
			mobileTextBox3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			mobileTextBox3.TextBackColor = System.Drawing.Color.Snow;
			mobileTextBox3.TextBoxStyle = dotNetLab.Widgets.MobileTextBox.TextBoxStyles.Mobile;
			mobileTextBox3.UIElementBinders = null;
			mobileTextBox3.WhitePattern = false;
			mobileTextBox1.ActiveColor = System.Drawing.Color.Cyan;
			mobileTextBox1.BackColor = System.Drawing.Color.Transparent;
			uIElementBinderInfo2.DBEngineIndex = 0;
			uIElementBinderInfo2.EnableCheckBox_One_Zero = false;
			uIElementBinderInfo2.FieldName = "Val";
			uIElementBinderInfo2.Filter = "Name='IP' ";
			uIElementBinderInfo2.Ptr = null;
			uIElementBinderInfo2.StoreInDB = true;
			uIElementBinderInfo2.StoreIntoDBRealTime = true;
			uIElementBinderInfo2.TableName = "TCP";
			uIElementBinderInfo2.ThisControl = mobileTextBox1;
			mobileTextBox1.DataBindingInfo = uIElementBinderInfo2;
			mobileTextBox1.DoubleValue = double.NaN;
			mobileTextBox1.EnableMobileRound = false;
			mobileTextBox1.EnableNullValue = false;
			mobileTextBox1.FillColor = System.Drawing.Color.Transparent;
			mobileTextBox1.FloatValue = float.NaN;
			mobileTextBox1.Font = new System.Drawing.Font("微软雅黑", 13f);
			mobileTextBox1.ForeColor = System.Drawing.Color.Black;
			mobileTextBox1.GreyPattern = false;
			mobileTextBox1.IntValue = -2147483648;
			mobileTextBox1.LineThickness = 2f;
			mobileTextBox1.Location = new System.Drawing.Point(187, 42);
			mobileTextBox1.MainBindableProperty = "";
			mobileTextBox1.Name = "mobileTextBox1";
			mobileTextBox1.Radius = -1;
			mobileTextBox1.Size = new System.Drawing.Size(187, 30);
			mobileTextBox1.StaticColor = System.Drawing.Color.DodgerBlue;
			mobileTextBox1.TabIndex = 8;
			mobileTextBox1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			mobileTextBox1.TextBackColor = System.Drawing.Color.Snow;
			mobileTextBox1.TextBoxStyle = dotNetLab.Widgets.MobileTextBox.TextBoxStyles.Mobile;
			mobileTextBox1.UIElementBinders = null;
			mobileTextBox1.WhitePattern = false;
			mobileTextBox2.ActiveColor = System.Drawing.Color.Cyan;
			mobileTextBox2.BackColor = System.Drawing.Color.Transparent;
			uIElementBinderInfo3.DBEngineIndex = 0;
			uIElementBinderInfo3.EnableCheckBox_One_Zero = false;
			uIElementBinderInfo3.FieldName = "Val";
			uIElementBinderInfo3.Filter = "Name='Port' ";
			uIElementBinderInfo3.Ptr = null;
			uIElementBinderInfo3.StoreInDB = true;
			uIElementBinderInfo3.StoreIntoDBRealTime = true;
			uIElementBinderInfo3.TableName = "TCP";
			uIElementBinderInfo3.ThisControl = mobileTextBox2;
			mobileTextBox2.DataBindingInfo = uIElementBinderInfo3;
			mobileTextBox2.DoubleValue = double.NaN;
			mobileTextBox2.EnableMobileRound = false;
			mobileTextBox2.EnableNullValue = false;
			mobileTextBox2.FillColor = System.Drawing.Color.Transparent;
			mobileTextBox2.FloatValue = float.NaN;
			mobileTextBox2.Font = new System.Drawing.Font("微软雅黑", 13f);
			mobileTextBox2.ForeColor = System.Drawing.Color.Black;
			mobileTextBox2.GreyPattern = false;
			mobileTextBox2.IntValue = -2147483648;
			mobileTextBox2.LineThickness = 2f;
			mobileTextBox2.Location = new System.Drawing.Point(187, 87);
			mobileTextBox2.MainBindableProperty = "";
			mobileTextBox2.Name = "mobileTextBox2";
			mobileTextBox2.Radius = -1;
			mobileTextBox2.Size = new System.Drawing.Size(187, 30);
			mobileTextBox2.StaticColor = System.Drawing.Color.DodgerBlue;
			mobileTextBox2.TabIndex = 9;
			mobileTextBox2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			mobileTextBox2.TextBackColor = System.Drawing.Color.Snow;
			mobileTextBox2.TextBoxStyle = dotNetLab.Widgets.MobileTextBox.TextBoxStyles.Mobile;
			mobileTextBox2.UIElementBinders = null;
			mobileTextBox2.WhitePattern = false;
			txb_LoopGapTime.ActiveColor = System.Drawing.Color.Cyan;
			txb_LoopGapTime.BackColor = System.Drawing.Color.Transparent;
			uIElementBinderInfo4.DBEngineIndex = 0;
			uIElementBinderInfo4.EnableCheckBox_One_Zero = false;
			uIElementBinderInfo4.FieldName = "Val";
			uIElementBinderInfo4.Filter = "Name='LoopGapTime' ";
			uIElementBinderInfo4.Ptr = null;
			uIElementBinderInfo4.StoreInDB = true;
			uIElementBinderInfo4.StoreIntoDBRealTime = true;
			uIElementBinderInfo4.TableName = "SerialPort";
			uIElementBinderInfo4.ThisControl = txb_LoopGapTime;
			txb_LoopGapTime.DataBindingInfo = uIElementBinderInfo4;
			txb_LoopGapTime.DoubleValue = double.NaN;
			txb_LoopGapTime.EnableMobileRound = true;
			txb_LoopGapTime.EnableNullValue = false;
			txb_LoopGapTime.FillColor = System.Drawing.Color.Transparent;
			txb_LoopGapTime.FloatValue = float.NaN;
			txb_LoopGapTime.Font = new System.Drawing.Font("微软雅黑", 13f);
			txb_LoopGapTime.ForeColor = System.Drawing.Color.Black;
			txb_LoopGapTime.GreyPattern = false;
			txb_LoopGapTime.IntValue = -2147483648;
			txb_LoopGapTime.LineThickness = 2f;
			txb_LoopGapTime.Location = new System.Drawing.Point(112, 140);
			txb_LoopGapTime.MainBindableProperty = "";
			txb_LoopGapTime.Name = "txb_LoopGapTime";
			txb_LoopGapTime.Radius = 29;
			txb_LoopGapTime.Size = new System.Drawing.Size(98, 30);
			txb_LoopGapTime.StaticColor = System.Drawing.Color.Gray;
			txb_LoopGapTime.TabIndex = 7;
			txb_LoopGapTime.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			txb_LoopGapTime.TextBackColor = System.Drawing.Color.Snow;
			txb_LoopGapTime.TextBoxStyle = dotNetLab.Widgets.MobileTextBox.TextBoxStyles.Mobile;
			txb_LoopGapTime.UIElementBinders = null;
			txb_LoopGapTime.WhitePattern = false;
			txb_COM.ActiveColor = System.Drawing.Color.Cyan;
			txb_COM.BackColor = System.Drawing.Color.Transparent;
			uIElementBinderInfo5.DBEngineIndex = 0;
			uIElementBinderInfo5.EnableCheckBox_One_Zero = false;
			uIElementBinderInfo5.FieldName = "Val";
			uIElementBinderInfo5.Filter = "Name='COM' ";
			uIElementBinderInfo5.Ptr = null;
			uIElementBinderInfo5.StoreInDB = true;
			uIElementBinderInfo5.StoreIntoDBRealTime = true;
			uIElementBinderInfo5.TableName = "SerialPort";
			uIElementBinderInfo5.ThisControl = txb_COM;
			txb_COM.DataBindingInfo = uIElementBinderInfo5;
			txb_COM.DoubleValue = double.NaN;
			txb_COM.EnableMobileRound = true;
			txb_COM.EnableNullValue = false;
			txb_COM.FillColor = System.Drawing.Color.Transparent;
			txb_COM.FloatValue = float.NaN;
			txb_COM.Font = new System.Drawing.Font("微软雅黑", 13f);
			txb_COM.ForeColor = System.Drawing.Color.Black;
			txb_COM.GreyPattern = false;
			txb_COM.IntValue = -2147483648;
			txb_COM.LineThickness = 2f;
			txb_COM.Location = new System.Drawing.Point(112, 52);
			txb_COM.MainBindableProperty = "";
			txb_COM.Name = "txb_COM";
			txb_COM.Radius = 29;
			txb_COM.Size = new System.Drawing.Size(98, 30);
			txb_COM.StaticColor = System.Drawing.Color.Gray;
			txb_COM.TabIndex = 8;
			txb_COM.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			txb_COM.TextBackColor = System.Drawing.Color.Snow;
			txb_COM.TextBoxStyle = dotNetLab.Widgets.MobileTextBox.TextBoxStyles.Mobile;
			txb_COM.UIElementBinders = null;
			txb_COM.WhitePattern = false;
			txb_BaudRate.ActiveColor = System.Drawing.Color.Cyan;
			txb_BaudRate.BackColor = System.Drawing.Color.Transparent;
			uIElementBinderInfo6.DBEngineIndex = 0;
			uIElementBinderInfo6.EnableCheckBox_One_Zero = false;
			uIElementBinderInfo6.FieldName = "Val";
			uIElementBinderInfo6.Filter = "Name='BaudRate' ";
			uIElementBinderInfo6.Ptr = null;
			uIElementBinderInfo6.StoreInDB = true;
			uIElementBinderInfo6.StoreIntoDBRealTime = true;
			uIElementBinderInfo6.TableName = "SerialPort";
			uIElementBinderInfo6.ThisControl = txb_BaudRate;
			txb_BaudRate.DataBindingInfo = uIElementBinderInfo6;
			txb_BaudRate.DoubleValue = double.NaN;
			txb_BaudRate.EnableMobileRound = true;
			txb_BaudRate.EnableNullValue = false;
			txb_BaudRate.FillColor = System.Drawing.Color.Transparent;
			txb_BaudRate.FloatValue = float.NaN;
			txb_BaudRate.Font = new System.Drawing.Font("微软雅黑", 13f);
			txb_BaudRate.ForeColor = System.Drawing.Color.Black;
			txb_BaudRate.GreyPattern = false;
			txb_BaudRate.IntValue = -2147483648;
			txb_BaudRate.LineThickness = 2f;
			txb_BaudRate.Location = new System.Drawing.Point(112, 97);
			txb_BaudRate.MainBindableProperty = "";
			txb_BaudRate.Name = "txb_BaudRate";
			txb_BaudRate.Radius = 29;
			txb_BaudRate.Size = new System.Drawing.Size(98, 30);
			txb_BaudRate.StaticColor = System.Drawing.Color.Gray;
			txb_BaudRate.TabIndex = 9;
			txb_BaudRate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			txb_BaudRate.TextBackColor = System.Drawing.Color.Snow;
			txb_BaudRate.TextBoxStyle = dotNetLab.Widgets.MobileTextBox.TextBoxStyles.Mobile;
			txb_BaudRate.UIElementBinders = null;
			txb_BaudRate.WhitePattern = false;
			txb_DataBits.ActiveColor = System.Drawing.Color.Cyan;
			txb_DataBits.BackColor = System.Drawing.Color.Transparent;
			uIElementBinderInfo7.DBEngineIndex = 0;
			uIElementBinderInfo7.EnableCheckBox_One_Zero = false;
			uIElementBinderInfo7.FieldName = "Val";
			uIElementBinderInfo7.Filter = "Name='DataBits' ";
			uIElementBinderInfo7.Ptr = null;
			uIElementBinderInfo7.StoreInDB = true;
			uIElementBinderInfo7.StoreIntoDBRealTime = true;
			uIElementBinderInfo7.TableName = "SerialPort";
			uIElementBinderInfo7.ThisControl = txb_DataBits;
			txb_DataBits.DataBindingInfo = uIElementBinderInfo7;
			txb_DataBits.DoubleValue = double.NaN;
			txb_DataBits.EnableMobileRound = true;
			txb_DataBits.EnableNullValue = false;
			txb_DataBits.FillColor = System.Drawing.Color.Transparent;
			txb_DataBits.FloatValue = float.NaN;
			txb_DataBits.Font = new System.Drawing.Font("微软雅黑", 13f);
			txb_DataBits.ForeColor = System.Drawing.Color.Black;
			txb_DataBits.GreyPattern = false;
			txb_DataBits.IntValue = -2147483648;
			txb_DataBits.LineThickness = 2f;
			txb_DataBits.Location = new System.Drawing.Point(316, 52);
			txb_DataBits.MainBindableProperty = "";
			txb_DataBits.Name = "txb_DataBits";
			txb_DataBits.Radius = 29;
			txb_DataBits.Size = new System.Drawing.Size(98, 30);
			txb_DataBits.StaticColor = System.Drawing.Color.Gray;
			txb_DataBits.TabIndex = 8;
			txb_DataBits.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			txb_DataBits.TextBackColor = System.Drawing.Color.Snow;
			txb_DataBits.TextBoxStyle = dotNetLab.Widgets.MobileTextBox.TextBoxStyles.Mobile;
			txb_DataBits.UIElementBinders = null;
			txb_DataBits.WhitePattern = false;
			txb_StopBits.ActiveColor = System.Drawing.Color.Cyan;
			txb_StopBits.BackColor = System.Drawing.Color.Transparent;
			uIElementBinderInfo8.DBEngineIndex = 0;
			uIElementBinderInfo8.EnableCheckBox_One_Zero = false;
			uIElementBinderInfo8.FieldName = "Val";
			uIElementBinderInfo8.Filter = "Name='StopBits' ";
			uIElementBinderInfo8.Ptr = null;
			uIElementBinderInfo8.StoreInDB = true;
			uIElementBinderInfo8.StoreIntoDBRealTime = true;
			uIElementBinderInfo8.TableName = "SerialPort";
			uIElementBinderInfo8.ThisControl = txb_StopBits;
			txb_StopBits.DataBindingInfo = uIElementBinderInfo8;
			txb_StopBits.DoubleValue = double.NaN;
			txb_StopBits.EnableMobileRound = true;
			txb_StopBits.EnableNullValue = false;
			txb_StopBits.FillColor = System.Drawing.Color.Transparent;
			txb_StopBits.FloatValue = float.NaN;
			txb_StopBits.Font = new System.Drawing.Font("微软雅黑", 13f);
			txb_StopBits.ForeColor = System.Drawing.Color.Black;
			txb_StopBits.GreyPattern = false;
			txb_StopBits.IntValue = -2147483648;
			txb_StopBits.LineThickness = 2f;
			txb_StopBits.Location = new System.Drawing.Point(316, 98);
			txb_StopBits.MainBindableProperty = "";
			txb_StopBits.Name = "txb_StopBits";
			txb_StopBits.Radius = 29;
			txb_StopBits.Size = new System.Drawing.Size(98, 30);
			txb_StopBits.StaticColor = System.Drawing.Color.Gray;
			txb_StopBits.TabIndex = 8;
			txb_StopBits.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			txb_StopBits.TextBackColor = System.Drawing.Color.Snow;
			txb_StopBits.TextBoxStyle = dotNetLab.Widgets.MobileTextBox.TextBoxStyles.Mobile;
			txb_StopBits.UIElementBinders = null;
			txb_StopBits.WhitePattern = false;
			txb_Parity.ActiveColor = System.Drawing.Color.Cyan;
			txb_Parity.BackColor = System.Drawing.Color.Transparent;
			uIElementBinderInfo9.DBEngineIndex = 0;
			uIElementBinderInfo9.EnableCheckBox_One_Zero = false;
			uIElementBinderInfo9.FieldName = "Val";
			uIElementBinderInfo9.Filter = "Name='Parity' ";
			uIElementBinderInfo9.Ptr = null;
			uIElementBinderInfo9.StoreInDB = true;
			uIElementBinderInfo9.StoreIntoDBRealTime = true;
			uIElementBinderInfo9.TableName = "SerialPort";
			uIElementBinderInfo9.ThisControl = txb_Parity;
			txb_Parity.DataBindingInfo = uIElementBinderInfo9;
			txb_Parity.DoubleValue = double.NaN;
			txb_Parity.EnableMobileRound = true;
			txb_Parity.EnableNullValue = false;
			txb_Parity.FillColor = System.Drawing.Color.Transparent;
			txb_Parity.FloatValue = float.NaN;
			txb_Parity.Font = new System.Drawing.Font("微软雅黑", 13f);
			txb_Parity.ForeColor = System.Drawing.Color.Black;
			txb_Parity.GreyPattern = false;
			txb_Parity.IntValue = -2147483648;
			txb_Parity.LineThickness = 2f;
			txb_Parity.Location = new System.Drawing.Point(316, 141);
			txb_Parity.MainBindableProperty = "";
			txb_Parity.Name = "txb_Parity";
			txb_Parity.Radius = 29;
			txb_Parity.Size = new System.Drawing.Size(98, 30);
			txb_Parity.StaticColor = System.Drawing.Color.Gray;
			txb_Parity.TabIndex = 8;
			txb_Parity.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			txb_Parity.TextBackColor = System.Drawing.Color.Snow;
			txb_Parity.TextBoxStyle = dotNetLab.Widgets.MobileTextBox.TextBoxStyles.Mobile;
			txb_Parity.UIElementBinders = null;
			txb_Parity.WhitePattern = false;
			textBlock9.BackColor = System.Drawing.Color.Transparent;
			textBlock9.BorderColor = System.Drawing.Color.Empty;
			textBlock9.BorderThickness = 0;
			textBlock9.DataBindingInfo = null;
			textBlock9.EnableFlag = true;
			textBlock9.EnableTextRenderHint = true;
			textBlock9.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock9.FlagColor = System.Drawing.Color.DodgerBlue;
			textBlock9.FlagThickness = 8;
			textBlock9.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock9.GapBetweenTextFlag = 10;
			textBlock9.LEDStyle = false;
			textBlock9.Location = new System.Drawing.Point(87, 137);
			textBlock9.MainBindableProperty = "轮询频率";
			textBlock9.Name = "textBlock9";
			textBlock9.Radius = 0;
			textBlock9.Size = new System.Drawing.Size(94, 23);
			textBlock9.TabIndex = 4;
			textBlock9.Text = "轮询频率";
			textBlock9.UIElementBinders = null;
			textBlock9.UnderLine = false;
			textBlock9.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock9.UnderLineThickness = 2f;
			textBlock9.Vertical = false;
			textBlock9.WhereReturn = 0;
			textBlock8.BackColor = System.Drawing.Color.Transparent;
			textBlock8.BorderColor = System.Drawing.Color.Empty;
			textBlock8.BorderThickness = 0;
			textBlock8.DataBindingInfo = null;
			textBlock8.EnableFlag = true;
			textBlock8.EnableTextRenderHint = true;
			textBlock8.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock8.FlagColor = System.Drawing.Color.DodgerBlue;
			textBlock8.FlagThickness = 8;
			textBlock8.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock8.GapBetweenTextFlag = 10;
			textBlock8.LEDStyle = false;
			textBlock8.Location = new System.Drawing.Point(87, 87);
			textBlock8.MainBindableProperty = "端口号";
			textBlock8.Name = "textBlock8";
			textBlock8.Radius = 0;
			textBlock8.Size = new System.Drawing.Size(76, 23);
			textBlock8.TabIndex = 5;
			textBlock8.Text = "端口号";
			textBlock8.UIElementBinders = null;
			textBlock8.UnderLine = false;
			textBlock8.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock8.UnderLineThickness = 2f;
			textBlock8.Vertical = false;
			textBlock8.WhereReturn = 0;
			textBlock7.BackColor = System.Drawing.Color.Transparent;
			textBlock7.BorderColor = System.Drawing.Color.Empty;
			textBlock7.BorderThickness = 0;
			textBlock7.DataBindingInfo = null;
			textBlock7.EnableFlag = true;
			textBlock7.EnableTextRenderHint = true;
			textBlock7.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock7.FlagColor = System.Drawing.Color.DodgerBlue;
			textBlock7.FlagThickness = 8;
			textBlock7.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock7.GapBetweenTextFlag = 10;
			textBlock7.LEDStyle = false;
			textBlock7.Location = new System.Drawing.Point(87, 42);
			textBlock7.MainBindableProperty = "IP";
			textBlock7.Name = "textBlock7";
			textBlock7.Radius = 0;
			textBlock7.Size = new System.Drawing.Size(45, 23);
			textBlock7.TabIndex = 6;
			textBlock7.Text = "IP";
			textBlock7.UIElementBinders = null;
			textBlock7.UnderLine = false;
			textBlock7.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock7.UnderLineThickness = 2f;
			textBlock7.Vertical = false;
			textBlock7.WhereReturn = 0;
			card1.BackColor = System.Drawing.Color.Transparent;
			card1.BorderColor = System.Drawing.Color.Gray;
			card1.BorderThickness = -1;
			card1.Controls.Add(textBlock1);
			card1.Controls.Add(textBlock7);
			card1.Controls.Add(mobileTextBox3);
			card1.Controls.Add(textBlock8);
			card1.Controls.Add(textBlock9);
			card1.Controls.Add(mobileTextBox1);
			card1.Controls.Add(mobileTextBox2);
			card1.CornerAlignment = dotNetLab.Widgets.Alignments.All;
			card1.DataBindingInfo = null;
			card1.Font = new System.Drawing.Font("微软雅黑", 11f);
			card1.HeadColor = System.Drawing.Color.DodgerBlue;
			card1.HeaderAlignment = dotNetLab.Widgets.Alignments.Left;
			card1.HeadHeight = 50;
			card1.ImagePos = new System.Drawing.Point(0, 0);
			card1.ImageSize = new System.Drawing.Size(0, 0);
			card1.Location = new System.Drawing.Point(82, 84);
			card1.MainBindableProperty = "card1";
			card1.Name = "card1";
			card1.NormalColor = System.Drawing.Color.Snow;
			card1.Radius = 10;
			card1.Size = new System.Drawing.Size(475, 200);
			card1.Source = null;
			card1.TabIndex = 10;
			card1.Text = "card1";
			card1.UIElementBinders = null;
			textBlock1.BackColor = System.Drawing.Color.Transparent;
			textBlock1.BorderColor = System.Drawing.Color.Empty;
			textBlock1.BorderThickness = -1;
			textBlock1.DataBindingInfo = null;
			textBlock1.EnableFlag = false;
			textBlock1.EnableTextRenderHint = false;
			textBlock1.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock1.FlagColor = System.Drawing.Color.DodgerBlue;
			textBlock1.FlagThickness = 5;
			textBlock1.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock1.ForeColor = System.Drawing.Color.White;
			textBlock1.GapBetweenTextFlag = 10;
			textBlock1.LEDStyle = false;
			textBlock1.Location = new System.Drawing.Point(12, 42);
			textBlock1.MainBindableProperty = "以太网设置";
			textBlock1.Name = "textBlock1";
			textBlock1.Radius = -1;
			textBlock1.Size = new System.Drawing.Size(27, 117);
			textBlock1.TabIndex = 10;
			textBlock1.Text = "以太网设置";
			textBlock1.UIElementBinders = null;
			textBlock1.UnderLine = false;
			textBlock1.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock1.UnderLineThickness = 2f;
			textBlock1.Vertical = true;
			textBlock1.WhereReturn = 0;
			card2.BackColor = System.Drawing.Color.Transparent;
			card2.BorderColor = System.Drawing.Color.Gray;
			card2.BorderThickness = -1;
			card2.Controls.Add(textBlock2);
			card2.Controls.Add(textBlock11);
			card2.Controls.Add(textBlock10);
			card2.Controls.Add(textBlock6);
			card2.Controls.Add(textBlock3);
			card2.Controls.Add(txb_LoopGapTime);
			card2.Controls.Add(txb_Parity);
			card2.Controls.Add(textBlock4);
			card2.Controls.Add(txb_StopBits);
			card2.Controls.Add(txb_DataBits);
			card2.Controls.Add(textBlock5);
			card2.Controls.Add(txb_COM);
			card2.Controls.Add(txb_BaudRate);
			card2.CornerAlignment = dotNetLab.Widgets.Alignments.All;
			card2.DataBindingInfo = null;
			card2.Font = new System.Drawing.Font("微软雅黑", 11f);
			card2.HeadColor = System.Drawing.Color.Crimson;
			card2.HeaderAlignment = dotNetLab.Widgets.Alignments.Up;
			card2.HeadHeight = 40;
			card2.ImagePos = new System.Drawing.Point(0, 0);
			card2.ImageSize = new System.Drawing.Size(0, 0);
			card2.Location = new System.Drawing.Point(82, 301);
			card2.MainBindableProperty = "card1";
			card2.Name = "card2";
			card2.NormalColor = System.Drawing.Color.Snow;
			card2.Radius = 10;
			card2.Size = new System.Drawing.Size(475, 200);
			card2.Source = null;
			card2.TabIndex = 10;
			card2.Text = "card1";
			card2.UIElementBinders = null;
			textBlock2.BackColor = System.Drawing.Color.Transparent;
			textBlock2.BorderColor = System.Drawing.Color.Empty;
			textBlock2.BorderThickness = -1;
			textBlock2.DataBindingInfo = null;
			textBlock2.EnableFlag = false;
			textBlock2.EnableTextRenderHint = false;
			textBlock2.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock2.FlagColor = System.Drawing.Color.DodgerBlue;
			textBlock2.FlagThickness = 5;
			textBlock2.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock2.ForeColor = System.Drawing.Color.White;
			textBlock2.GapBetweenTextFlag = 10;
			textBlock2.LEDStyle = false;
			textBlock2.Location = new System.Drawing.Point(159, 8);
			textBlock2.MainBindableProperty = "串口设置";
			textBlock2.Name = "textBlock2";
			textBlock2.Radius = -1;
			textBlock2.Size = new System.Drawing.Size(120, 28);
			textBlock2.TabIndex = 10;
			textBlock2.Text = "串口设置";
			textBlock2.UIElementBinders = null;
			textBlock2.UnderLine = false;
			textBlock2.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock2.UnderLineThickness = 2f;
			textBlock2.Vertical = false;
			textBlock2.WhereReturn = 0;
			textBlock11.BackColor = System.Drawing.Color.Transparent;
			textBlock11.BorderColor = System.Drawing.Color.Empty;
			textBlock11.BorderThickness = 0;
			textBlock11.DataBindingInfo = null;
			textBlock11.EnableFlag = true;
			textBlock11.EnableTextRenderHint = true;
			textBlock11.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock11.FlagColor = System.Drawing.Color.Crimson;
			textBlock11.FlagThickness = 8;
			textBlock11.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock11.GapBetweenTextFlag = 10;
			textBlock11.LEDStyle = false;
			textBlock11.Location = new System.Drawing.Point(234, 147);
			textBlock11.MainBindableProperty = "奇偶性 : ";
			textBlock11.Name = "textBlock11";
			textBlock11.Radius = 0;
			textBlock11.Size = new System.Drawing.Size(76, 23);
			textBlock11.TabIndex = 6;
			textBlock11.Text = "奇偶性 : ";
			textBlock11.UIElementBinders = null;
			textBlock11.UnderLine = false;
			textBlock11.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock11.UnderLineThickness = 2f;
			textBlock11.Vertical = false;
			textBlock11.WhereReturn = 0;
			textBlock10.BackColor = System.Drawing.Color.Transparent;
			textBlock10.BorderColor = System.Drawing.Color.Empty;
			textBlock10.BorderThickness = 0;
			textBlock10.DataBindingInfo = null;
			textBlock10.EnableFlag = true;
			textBlock10.EnableTextRenderHint = true;
			textBlock10.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock10.FlagColor = System.Drawing.Color.Crimson;
			textBlock10.FlagThickness = 8;
			textBlock10.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock10.GapBetweenTextFlag = 10;
			textBlock10.LEDStyle = false;
			textBlock10.Location = new System.Drawing.Point(234, 104);
			textBlock10.MainBindableProperty = "停止位：";
			textBlock10.Name = "textBlock10";
			textBlock10.Radius = 0;
			textBlock10.Size = new System.Drawing.Size(76, 23);
			textBlock10.TabIndex = 6;
			textBlock10.Text = "停止位：";
			textBlock10.UIElementBinders = null;
			textBlock10.UnderLine = false;
			textBlock10.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock10.UnderLineThickness = 2f;
			textBlock10.Vertical = false;
			textBlock10.WhereReturn = 0;
			textBlock6.BackColor = System.Drawing.Color.Transparent;
			textBlock6.BorderColor = System.Drawing.Color.Empty;
			textBlock6.BorderThickness = 0;
			textBlock6.DataBindingInfo = null;
			textBlock6.EnableFlag = true;
			textBlock6.EnableTextRenderHint = true;
			textBlock6.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock6.FlagColor = System.Drawing.Color.Crimson;
			textBlock6.FlagThickness = 8;
			textBlock6.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock6.GapBetweenTextFlag = 10;
			textBlock6.LEDStyle = false;
			textBlock6.Location = new System.Drawing.Point(234, 56);
			textBlock6.MainBindableProperty = "数据位：";
			textBlock6.Name = "textBlock6";
			textBlock6.Radius = 0;
			textBlock6.Size = new System.Drawing.Size(76, 23);
			textBlock6.TabIndex = 6;
			textBlock6.Text = "数据位：";
			textBlock6.UIElementBinders = null;
			textBlock6.UnderLine = false;
			textBlock6.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock6.UnderLineThickness = 2f;
			textBlock6.Vertical = false;
			textBlock6.WhereReturn = 0;
			textBlock3.BackColor = System.Drawing.Color.Transparent;
			textBlock3.BorderColor = System.Drawing.Color.Empty;
			textBlock3.BorderThickness = 0;
			textBlock3.DataBindingInfo = null;
			textBlock3.EnableFlag = true;
			textBlock3.EnableTextRenderHint = true;
			textBlock3.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock3.FlagColor = System.Drawing.Color.Crimson;
			textBlock3.FlagThickness = 8;
			textBlock3.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock3.GapBetweenTextFlag = 10;
			textBlock3.LEDStyle = false;
			textBlock3.Location = new System.Drawing.Point(12, 52);
			textBlock3.MainBindableProperty = "端口名：";
			textBlock3.Name = "textBlock3";
			textBlock3.Radius = 0;
			textBlock3.Size = new System.Drawing.Size(76, 23);
			textBlock3.TabIndex = 6;
			textBlock3.Text = "端口名：";
			textBlock3.UIElementBinders = null;
			textBlock3.UnderLine = false;
			textBlock3.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock3.UnderLineThickness = 2f;
			textBlock3.Vertical = false;
			textBlock3.WhereReturn = 0;
			textBlock4.BackColor = System.Drawing.Color.Transparent;
			textBlock4.BorderColor = System.Drawing.Color.Empty;
			textBlock4.BorderThickness = 0;
			textBlock4.DataBindingInfo = null;
			textBlock4.EnableFlag = true;
			textBlock4.EnableTextRenderHint = true;
			textBlock4.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock4.FlagColor = System.Drawing.Color.Crimson;
			textBlock4.FlagThickness = 8;
			textBlock4.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock4.GapBetweenTextFlag = 10;
			textBlock4.LEDStyle = false;
			textBlock4.Location = new System.Drawing.Point(12, 97);
			textBlock4.MainBindableProperty = "波特率";
			textBlock4.Name = "textBlock4";
			textBlock4.Radius = 0;
			textBlock4.Size = new System.Drawing.Size(76, 23);
			textBlock4.TabIndex = 5;
			textBlock4.Text = "波特率";
			textBlock4.UIElementBinders = null;
			textBlock4.UnderLine = false;
			textBlock4.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock4.UnderLineThickness = 2f;
			textBlock4.Vertical = false;
			textBlock4.WhereReturn = 0;
			textBlock5.BackColor = System.Drawing.Color.Transparent;
			textBlock5.BorderColor = System.Drawing.Color.Empty;
			textBlock5.BorderThickness = 0;
			textBlock5.DataBindingInfo = null;
			textBlock5.EnableFlag = true;
			textBlock5.EnableTextRenderHint = true;
			textBlock5.FlagAlign = dotNetLab.Widgets.Alignments.Left;
			textBlock5.FlagColor = System.Drawing.Color.Crimson;
			textBlock5.FlagThickness = 8;
			textBlock5.Font = new System.Drawing.Font("微软雅黑", 12f);
			textBlock5.GapBetweenTextFlag = 10;
			textBlock5.LEDStyle = false;
			textBlock5.Location = new System.Drawing.Point(12, 147);
			textBlock5.MainBindableProperty = "轮询频率";
			textBlock5.Name = "textBlock5";
			textBlock5.Radius = 0;
			textBlock5.Size = new System.Drawing.Size(94, 23);
			textBlock5.TabIndex = 4;
			textBlock5.Text = "轮询频率";
			textBlock5.UIElementBinders = null;
			textBlock5.UnderLine = false;
			textBlock5.UnderLineColor = System.Drawing.Color.DarkGray;
			textBlock5.UnderLineThickness = 2f;
			textBlock5.Vertical = false;
			textBlock5.WhereReturn = 0;
			base.ClientSize = new System.Drawing.Size(660, 552);
			base.Controls.Add(card2);
			base.Controls.Add(card1);
			base.Name = "TCPNetConnectForm";
			Text = "视觉通讯";
			base.TitlePos = new System.Drawing.Point(70, 15);
			base.Controls.SetChildIndex(card1, 0);
			base.Controls.SetChildIndex(card2, 0);
			card1.ResumeLayout(false);
			card2.ResumeLayout(false);
			ResumeLayout(false);
		}
	}
}
